files:
  - source: /docs/*.md
    translation: /docs/%locale_with_underscore%/%original_file_name%
  - source: /docs/archive/tiramisu/*.md
    translation: /docs/%locale_with_underscore%/archive/tiramisu/%original_file_name%
  - source: /docs/aroma/*.md
    translation: /docs/%locale_with_underscore%/aroma/%original_file_name%
  - source: /docs/vwii/*.md
    translation: /docs/%locale_with_underscore%/vwii/%original_file_name%
  - source: /docs/.vitepress/i18n/strings/en_US.json
    translation: /docs/.vitepress/i18n/strings/%locale_with_underscore%.json
